/*
 Generated by typeshare 1.13.4
*/

export interface LabelCount {
	label: string;
	count: number;
}

export interface AnalyticsAggregates {
	total_sessions: number;
	average_week: number;
	death_cause_distribution: LabelCount[];
	archetype_distribution: LabelCount[];
	goal_distribution: LabelCount[];
}

export interface AnalyticsEventPayload {
	session_id: string;
	device_id_hash: string;
	event_type: string;
	week: number;
	archetype?: string;
	event_data: Record<string, unknown>;
}

export interface AnalyticsIngestResponse {
	ok: boolean;
}

export interface HealthResponse {
	status: string;
	db: string;
}

export interface LeaderboardEntry {
	session_id: string;
	week: number;
	archetype?: string;
	game_over_type?: string;
	reached_second_term: boolean;
}

